name: Lint

on:
    push:
        branches: ['master']
    pull_request:
        branches: ['master']
        types: [opened, reopened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest

        container: node:14.20-bullseye

        steps:
            # Build project
            - name: Check out code from repository
              uses: actions/checkout@v3
            - run: npm ci

            - name: Lint
              run: npm run lint & npm run prettier
