name: Version check

on:
    pull_request:
        branches: ['master']
        types: [opened, reopened, synchronize]

jobs:
    version_check:
        runs-on: ubuntu-latest

        container: node:14.20-alpine

        steps:
            # Build project
            - name: Check out code from repository
              uses: actions/checkout@v3
            - name: Verifying version availability
              run: npm run check-version
